/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoidioma;

import java.applet.AudioClip;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER-PC
 */
public class Juego extends javax.swing.JFrame {

    /**
     * Creates new form Juego
     */
    public Juego() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnJugar = new javax.swing.JButton();
        lblDibujo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setText("SALIR");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 140, 70));

        btnInstrucciones.setText("INSTRUCCIONES");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 140, 60));

        btnJugar.setText("JUGAR");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 140, 50));

        lblDibujo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idioma/icono.gif"))); // NOI18N
        getContentPane().add(lblDibujo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 420, 240));

        lblTitulo.setFont(new java.awt.Font("Aharoni", 0, 45)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(204, 0, 51));
        lblTitulo.setText("Aprende  Otomi Jugando");
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 560, 120));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idioma/fondo.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
       AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/sonidito.wav"));
        sonido.play();
        System.exit(0);
        sonido.stop();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/instrucciones.wav"));
        sonido.play();
        
        JOptionPane.showMessageDialog(null,"Bienvenido...\n\n\n - Cuando seleccione el boton Jugar "
            +"\n podra empezar el juego."
            +"\n el cual conciste en colocar el nombre de la imagen"
            +"\n que aparece en pantalla,"
            +"\n pero en otomi."
            +"\n El apartado donde se pondra la palabara debe estar en minusculas,"
            +"\n de otra fora se considerara como si estuviera mal la respuesta."
            +"\n se le daran 3 vidas para comenzar si fracasa perder");
        sonido.stop();
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        AudioClip sonido = java.applet.Applet.newAudioClip(getClass().getResource("/sonidito.wav"));
        sonido.play();
        PRINCIPAL juego = new PRINCIPAL();
        juego.setVisible(true);
        this.setVisible(false);
        sonido.stop();
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblDibujo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
