/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package juegoidioma;

import java.applet.AudioClip;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_OPTION;

/**
 *
 * @author ACER-PC
 */
public class PRINCIPAL extends javax.swing.JFrame {

    Respuesta[] respuestaImagenes;
    private int numero;
    private int vida;
    private String resultado;
    private AudioClip sonido;
    private BufferedImage imageActual;

    public PRINCIPAL() {
        initComponents();

        sonido = java.applet.Applet.newAudioClip(getClass().getResource("/principal.wav"));
        sonido.play();
        armarImagenes();
        vidas.setText("5");
        mostrarImagenesPantalla();
    }

    public void armarImagenes() {
        respuestaImagenes = new Respuesta[20];

        respuestaImagenes[0] = new Respuesta("mpefi", "/imagenes/trabajar.jpg", "/imagenes/trabajar1.jpg", "/imagenes/trabajar2.jpg");
        respuestaImagenes[1] = new Respuesta("nthe'tahe'mi", "/imagenes/leer.jpg", "/imagenes/leer.jpg", "/imagenes/leer.jpg");
        respuestaImagenes[2] = new Respuesta("nuni", "/imagenes/balon.jpg", "/imagenes/balon2.jpg", "/imagenes/balon3.jpg");
        respuestaImagenes[3] = new Respuesta("peni", "/imagenes/lavar.jpg", "/imagenes/lavar2.jpg", "/imagenes/lavar3.jpg");
        respuestaImagenes[4] = new Respuesta("zajua", "/imagenes/puerco.jpg", "/imagenes/puerco.jpg", "/imagenes/puerco.jpg");
        respuestaImagenes[5] = new Respuesta("kunthe,", "/imagenes/nadar.jpg", "/imagenes/nadar2.jpg", "/imagenes/nadar.jpg");
        respuestaImagenes[6] = new Respuesta("tuhu", "/imagenes/cantar.jpg", "/imagenes/cantar.jpg", "/imagenes/cantar.jpg");
        respuestaImagenes[7] = new Respuesta("ähä", "/imagenes/dormir3.jpg", "/imagenes/dormir.png", "/imagenes/dormir.jpg");
        respuestaImagenes[8] = new Respuesta("jua", "/imagenes/conejo.jpg", "/imagenes/conejo.jpg", "/imagenes/conejo.jpg");
        respuestaImagenes[9] = new Respuesta("koraso", "/imagenes/corazon.jpg", "/imagenes/corazon2.jpg", "/imagenes/corazon3.jpg");
        respuestaImagenes[10] = new Respuesta("za", "/imagenes/arbol.jpg", "/imagenes/arbol2.jpg", "/imagenes/arbol.jpg");
        respuestaImagenes[11] = new Respuesta("nei", "/imagenes/bailar.jpg", "/imagenes/bailar.jpg", "/imagenes/bailar.jpg");
        respuestaImagenes[12] = new Respuesta("nu", "/imagenes/ver.jpg", "/imagenes/ver2.jpg", "/imagenes/ver.jpg");
        respuestaImagenes[13] = new Respuesta("hñe", "/imagenes/vestirse.jpg", "/imagenes/vestirse.jpg", "/imagenes/vestirse.jpg");
        respuestaImagenes[14] = new Respuesta("de'mxi", "/imagenes/jitomate.jpg", "/imagenes/jitomate2.jpg", "/imagenes/jitomate.jpg");
        respuestaImagenes[15] = new Respuesta("arroz", "/imagenes/arroz.jpg", "/imagenes/arroz.jpg", "/imagenes/arroz.jpg");
        respuestaImagenes[16] = new Respuesta("baga", "/imagenes/vaca.jpg", "/imagenes/vaca.jpg", "/imagenes/vaca.jpg");
        respuestaImagenes[17] = new Respuesta("fani", "/imagenes/caballo.jpg", "/imagenes/caballo.jpg", "/imagenes/caballo.jpg");
        respuestaImagenes[18] = new Respuesta("ju", "/imagenes/frijol2.jpg", "/imagenes/frijol2.jpg", "/imagenes/frijol2.jpg");
        respuestaImagenes[19] = new Respuesta("tihi", "/imagenes/correr.jpg", "/imagenes/correr.jpg", "/imagenes/correr.jpg");

        Random rnd = new Random();

        for (int i = 0; i < respuestaImagenes.length; i++) {
            int aleatorio = (int) (rnd.nextDouble() * 19);
            respuestaImagenes[i] = respuestaImagenes[aleatorio];
        }
    }

    public void mostrarImagenesPantalla() {
        ImageIcon fondo = new ImageIcon(getClass().getResource(respuestaImagenes[numero].getDuda1()));
        imagen1.setIcon(new ImageIcon(fondo.getImage().getScaledInstance(imagen1.getWidth(), imagen1.getHeight(), Image.SCALE_REPLICATE)));

        fondo = new ImageIcon(getClass().getResource(respuestaImagenes[numero].getDuda2()));
        imagen2.setIcon(new ImageIcon(fondo.getImage().getScaledInstance(imagen2.getWidth(), imagen2.getHeight(), Image.SCALE_REPLICATE)));

        fondo = new ImageIcon(getClass().getResource(respuestaImagenes[numero].getDuda3()));
        imagen3.setIcon(new ImageIcon(fondo.getImage().getScaledInstance(imagen3.getWidth(), imagen3.getHeight(), Image.SCALE_REPLICATE)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerificar = new javax.swing.JButton();
        btnRespuesta = new javax.swing.JButton();
        imagen2 = new javax.swing.JLabel();
        vidas = new javax.swing.JTextField();
        cajaRespuesta = new javax.swing.JTextField();
        imagen1 = new javax.swing.JLabel();
        imagen3 = new javax.swing.JLabel();
        Carita = new javax.swing.JLabel();
        btnReproducir = new javax.swing.JButton();
        btnParar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 127, 40));

        btnRespuesta.setText("Ver Respuesta");
        btnRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespuestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 127, 45));
        getContentPane().add(imagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 0, 430, 310));
        getContentPane().add(vidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 45, 51));

        cajaRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajaRespuestaActionPerformed(evt);
            }
        });
        cajaRespuesta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cajaRespuestaKeyPressed(evt);
            }
        });
        getContentPane().add(cajaRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 180, -1));
        getContentPane().add(imagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 86, 140));
        getContentPane().add(imagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 97, 136));

        Carita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idioma/ico.gif"))); // NOI18N
        Carita.setText("jLabel1");
        getContentPane().add(Carita, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 90, 60));

        btnReproducir.setText("Reproducir");
        btnReproducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReproducirActionPerformed(evt);
            }
        });
        getContentPane().add(btnReproducir, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, -1, -1));

        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });
        getContentPane().add(btnParar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        btnInstrucciones.setText("Instrucciones");
        btnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstruccionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, -1, -1));

        btnMenu.setText("Volver al Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 150, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/idioma/pigeonotomilrgweb__16053.1397090012.1280.1280.jpg"))); // NOI18N
        lblFondo.setText("jLabel1");
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 780, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        AudioClip sonido1 = java.applet.Applet.newAudioClip(getClass().getResource("/sonidito.wav"));
        sonido1.play();
        if (cajaRespuesta.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "No hay palabra escrita...");
        } else if (cajaRespuesta.getText().equals(respuestaImagenes[numero].getRespuesta())) {
            JOptionPane.showMessageDialog(null, "Bien hecho...");
            numero = numero + 1;
            if (numero == 20) {
                Triunfo t = new Triunfo();
                t.setVisible(true);
                this.setVisible(false);
                sonido.stop();

            }
            mostrarImagenesPantalla();
            cajaRespuesta.setText(null);
            int aumento = 0;
            vida = Integer.parseInt(vidas.getText());
            vida = vida + aumento;
            resultado = vida + "";
            vidas.setText(resultado);
        } else {
            JOptionPane.showMessageDialog(null, "Sigue Intentando...");
            cajaRespuesta.setText(null);
            int descuento = 1;
            vida = Integer.parseInt(vidas.getText());
            vida = vida - descuento;
            resultado = vida + "";
            vidas.setText(resultado);
            if (vida == 0) {
                FinDeJuego f = new FinDeJuego();
                f.setVisible(true);
                this.setVisible(false);
                sonido.stop();
            }
        }
        sonido1.stop();
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void cajaRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajaRespuestaActionPerformed
        //
    }//GEN-LAST:event_cajaRespuestaActionPerformed

    private void cajaRespuestaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cajaRespuestaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnVerificarActionPerformed(null);

        }
    }//GEN-LAST:event_cajaRespuestaKeyPressed

    private void btnRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaActionPerformed
        AudioClip sonido1 = java.applet.Applet.newAudioClip(getClass().getResource("/sonidito.wav"));
        sonido1.play();
        int respuesta = JOptionPane.showConfirmDialog(null, "Te costara una vida Ver la respuesta...", "", JOptionPane.YES_NO_OPTION);
        if (respuesta == YES_NO_OPTION) {
            JOptionPane.showMessageDialog(null, "La palabra es: " + respuestaImagenes[numero].getRespuesta());
            cajaRespuesta.setText(null);
            int descuento = 1;
            vida = Integer.parseInt(vidas.getText());
            vida = vida - descuento;
            resultado = vida + "";
            vidas.setText(resultado);
            //FinDeJuego f = new FinDeJuego();
            //f.setVisible(true);
            //this.setVisible(false);

        }

        sonido1.stop();
    }//GEN-LAST:event_btnRespuestaActionPerformed

    private void btnReproducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReproducirActionPerformed
        sonido.play();
    }//GEN-LAST:event_btnReproducirActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        sonido.stop();
    }//GEN-LAST:event_btnPararActionPerformed

    private void btnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstruccionesActionPerformed
        AudioClip sonido1 = java.applet.Applet.newAudioClip(getClass().getResource("/sonidito.wav"));
        sonido1.play();
        JOptionPane.showMessageDialog(null, "Tiene que anotar en el "
                + "\n recuadro de texto"
                + "\n el vervo de la imagen o el nombre de lo que aparece en la imagem"
                + "\n en Otomi."
                + "\n pero en otomi."
        );
        sonido1.stop();
    }//GEN-LAST:event_btnInstruccionesActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Juego j = new Juego();
        j.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carita;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnReproducir;
    private javax.swing.JButton btnRespuesta;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JTextField cajaRespuesta;
    private javax.swing.JLabel imagen1;
    private javax.swing.JLabel imagen2;
    private javax.swing.JLabel imagen3;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTextField vidas;
    // End of variables declaration//GEN-END:variables
}
